<html><head><meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"><title>Resource error</title><link rel="stylesheet" href="obix_doc.css" type="text/css"><meta name="generator" content="DocBook XSL Stylesheets V1.72.0"><link rel="start" href="index.html" title="Obix programming language documentation"><link rel="up" href="error_handling.html" title="Chapter 13. Runtime error handling"><link rel="prev" href="program_error.html" title="Program error"><link rel="next" href="user_input_error.html" title="User input error"><script type="text/javascript">
        
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-22290805-1']);
          _gaq.push(['_trackPageview']);
        
          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        
    </script></head><body bgcolor="white" text="black" link="#0000FF" vlink="#840084" alink="#0000FF"><div class="navheader"><table width="100%" summary="Navigation header"><tr><th colspan="3" align="center">Resource error</th></tr><tr><td width="20%" align="left"><a accesskey="p" href="program_error.html">Prev</a> </td><th width="60%" align="center">Chapter 13. Runtime error handling</th><td width="20%" align="right"> <a accesskey="n" href="user_input_error.html">Next</a></td></tr></table><hr></div><div class="section" lang="en"><div class="titlepage"><div><div><h2 class="title" style="clear: both"><a name="resource_error"></a>Resource error</h2></div></div></div><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><table border="0" summary="Note"><tr><td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td><th align="left">Note</th></tr><tr><td align="left" valign="top">Please note that this chapter is incomplete. An update will be published in the future.</td></tr></table></div><div class="simplesect" lang="en"><div class="titlepage"><div><div><h3 class="title"><a name="resource_error_description"></a>Description</h3></div></div></div><p>A <em class="firstterm">resource error</em> is an error that appears at runtime due to the unavailability or the malfunction of a resource needed by the application. A resource error disrupts the normal operation of an application.</p><p>Examples of resource errors are:</p><div class="itemizedlist"><ul type="disc"><li><p>a file cannot be accessed because it has been deleted or locked by another process</p></li><li><p>a network connection is unavailable</p></li><li><p>a database error occurs suddenly due to a shutdown of the database server</p></li></ul></div><p>Although <span class="emphasis"><em>program</em></span> errors and <span class="emphasis"><em>resource</em></span> errors both create problems at runtime, there is an important difference between these two kinds of runtime errors. As explained in a previous section, program errors are unintentionally introduced by the programmer; therefore they cannot be anticipated and they appear randomly at any location in the source code. On the other hand, resource errors can very well be anticipated, because they can only appear when a resource is used in a script. Hence, a programmer should always consider the case of a resource error, and handle it appropriately, especially if he or she wants to write robust and reliable, or fault-tolerant software. The following section explains how to do this.</p></div><div class="simplesect" lang="en"><div class="titlepage"><div><div><h3 class="title"><a name="resource_error_handling"></a>Customized resource error handling</h3></div></div></div><p>Whenever an application is executed, scripts call other scripts. For example, a main script <code class="code">script1</code> calls <code class="code">script2</code>, then <code class="code">script2</code> calls <code class="code">script3</code>, and <code class="code">script3</code> calls <code class="code">script4</code>. A script that calls another script is frequently named the <em class="firstterm">client script</em>, and the called script is then named the <em class="firstterm">supplier script</em>.</p><p>Now suppose that a supplier script needs a resource to properly execute its task. What should this script do in case of a resource error? This question is similar to asking: What should a worker do if he has no more bricks to build a wall? In practice he will just tell his superior who will then decide about what to do. The same is true for any supplier script. A supplier script cannot know how to handle the error in a way that would suit every client script. The best it can do is to simply return information about the error. The client script then handles the error in any way that is appropriate for the given case. If it cannot handle it itself, then it also just returns the error to its client script (that's like a superior who informs his superior about the lack of bricks). Thus, the error can bubble up the called scripts, until there is a client script that handles the error.</p><p>A concrete example would be a client script that calls a supplier script to get current exchange rates. If the supplier does this by retrieving data over the net (e.g. using a webservice), and the net is not available, then it just informs the client script about the failure. The client script might then try to retrieve the data from a local file that stores the most recent data successfully retrieved from the net, possibly by calling another supplier script. If this also fails, the script returns an error to its client script, informing it about the failure to get the exchange rates.</p><p>The recommended way to pass information about a resource error from a supplier to a client script is to provide an output argument in the supplier script that returns an error in case of a failure. The identifier of this output argument is typically <code class="code">o_error</code> and its type is a child-type of <code class="code">ty_resource_error</code>. In case of a failure, <code class="code">o_error</code> contains an object describing the problem, and if the operation is successful, <code class="code">o_error</code> is <code class="code">void</code>. Therefore property <code class="code">voidable</code> must explicitly be set to <code class="code">yes</code>. Thus, the typical definition of an output argument that returns a resource error looks like this:</p><pre class="programlisting">out error type:resource_error voidable:yes end</pre><p>It goes without saying that each client script should always consciously check the state of any error returned by a supplier script. The examples in the next section show how to do this.</p><div class="note" style="margin-left: 0.5in; margin-right: 0.5in;"><table border="0" summary="Note"><tr><td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td><th align="left">Note</th></tr><tr><td align="left" valign="top"><p>In this context it is useful (and amusing) to mention command number 6 of <em class="citetitle">The Ten Commandments for C Programmers</em>, written in Old English by Henry Spencer (see annotated version at http://www.lysator.liu.se/c/ten-commandments.html; it's really worth a reading):</p><p>[<span class="citation">If a function be advertised to return an error code in the event of difficulties, thou shalt check for that code, yea, even though the checks triple the size of thy code and produce aches in thy typing fingers, for if thou thinkest "it cannot happen to me", the gods shall surely punish thee for thy arrogance.</span>]</p></td></tr></table></div><p>An interesting question is: What happens if the lazy or sloppy programmer does <span class="emphasis"><em>not</em></span> check for errors.</p><p>In most cases, a program error will occur soon or later. But there is no guarantee for a program error. The consequence can also be a wrong result stored in a database, and discovered only after the software has been shipped to 1000000 customers! If the programmer is lucky, a program error will appear immediately, so that he or she is forced to improve the code. (Remark: the programmer really has to be lucky, because resource errors tend to appear less often during the development phase, in which the programmer has set up a much less error-prone environment (e.g. local files instead of files on a remote server, local webservice instead of a 'real' webservice, etc.)). For example, if the result of a command is a string object that is <code class="code">void</code> in case of an error, then a 'void object' program error appears immediately if the program immediately tries to execute a feature on the string, for example a conversion to lowercase letters. But if the result is simply stored to a database field that allows <code class="code">void</code> values, then the error might stay undiscovered until detected by an unlucky user.</p></div><div class="simplesect" lang="en"><div class="titlepage"><div><div><h3 class="title"><a name="resource_error_examples"></a>Examples</h3></div></div></div><p>Suppose a service command is used to write a <code class="code">date</code> to a text file in a standardized ISO 8601 format (e.g. 2008-01-18). The command has two input arguments: the date to be stored, and the file handle to which the date is to be stored.</p><p>As a file operation can always fail, the command also has an output argument that returns a <code class="code">file_error</code> object in case of a failure.</p><p>This leads to the following code:</p><pre class="programlisting">service error_handling_examples

   command store_date_to_file
      in date type:simple_date end                 // the date to be stored
      in new_or_existing_file type:file end        // the file used to store the date
      
      out error type:file_error voidable:yes end   // returns any file problems encountered
      
      script
         o_error = se_file.store_string_to_new_or_existing_file ( &amp;
            string = i_date.to_string &amp;
            file = i_new_or_existing_file )
      end
   end

end service</pre><p>The script converts the <code class="code">date</code> to a standardized <code class="code">string</code>, and then uses the <code class="code">string</code>'s <code class="code">store_to_new_or_existing_file</code> command to store the date as text in a file. In case of an error returned by <code class="code">store_to_new_or_existing_file</code>, this error is simply passed to the client of our service command.</p><p>Let's now create another service command that makes a backup of some data, and then stores the date of the last backup in a text file. We can do this by using the previously defined <code class="code">store_date_to_file</code> service command. In case of a failure to store the last backup date in a file, we simply display an error message on the system console:</p><pre class="programlisting">service error_handling_examples

   // this attribute defines the file used to store the date of the last backup
   attribute last_backup_date_file type: file &amp;
      default: fa_file.create ( fa_file_path.create ( '''c:\temp\last_backup_date.txt'''.value ) ) end

   command do_backup
      script
         // do backup (instructions not shown here)
         // ...
         
         // now store date of this backup in text file

         // get today's date
         const simple_date last_backup_date = se_simple_date.current_date
         
         // use 'co_store_date_to_file' to store the date
         // in case of a failure, 'error' holds the error returned by 'co_store_date_to_file'
         const file_error error = co_store_date_to_file ( &amp;
            date = c_last_backup_date &amp;
            new_or_existing_file = a_last_backup_date_file )

         // display a message in case of an error
         if c_error #r void then
            system.console.write_line ( """Last backup date ({{c_last_backup_date.to_string}})
could not be stored to file 
"{{a_last_backup_date_file.to_string}}"""" )
         end if
      end
   end

end service</pre><p>In case of an error, the following message is displayed:</p><pre class="screen">Last backup date (Jan 18, 2008)
could not be stored to file
"c:\temp\last_backup_date.txt"</pre><p>As we defined a <code class="code">store_date_to_file</code> service command, it is logical to also define a counterpart, namely command <code class="code">restore_date_from_file</code></p><p>This command has one input argument which is the file from which the date is to be restored.</p><p>The date restored from the file is returned with output argument <code class="code">result</code>. Because reading from a file can fail at runtime, we add a second output argument, <code class="code">error</code>, to signal any file problems to the client script. Each time this command is executed, there are two possible outcomes:</p><div class="itemizedlist"><ul type="disc"><li><p>the operation succeeded: <code class="code">o_result</code> contains the date restored from file, and <code class="code">o_error</code> is <code class="code">void</code></p></li><li><p>the operation failed: <code class="code">o_result</code> is <code class="code">void</code>, and <code class="code">o_error</code> contains the error encountered with the attempt to read the file</p></li></ul></div><p>This condition can easily be expressed with an exclusive or (<code class="code">xor</code>) operator. Either <code class="code">o_result</code> or <code class="code">o_error</code> is different from <code class="code">void</code>, but not both. Hence we use contract programming to ensure this condition (see <a href="contract_programming.html" title="Chapter 17. Contract programming">Chapter 17, <i>Contract programming</i></a> for more information about contract programming.</p><p>Thus, the code looks like this:</p><pre class="programlisting">service error_handling_examples

   command restore_date_from_file
      in existing_file type:file check: i_existing_file.exists end // the file in which the date is stored
      
      out result type:simple_date voidable:yes end                 // the date read from the file
      out error type:resource_error voidable:yes end               // any problem encountered with file reading
      out_check check: i_result #r void xor i_error #r void end    // exactly one output argument must be void
      
      script

         // read the content of the text file into a 'string' object
         var string date_in_file // holds the string read from file
         se_file.restore_string_from_file ( &amp;
            file = i_existing_file ) &amp;
            ( v_date_in_file = o_result &amp;
            o_error = o_error )

         // if the operation failed, leave immediately            
         if o_error #r void then
            exit script
         end if
         
         // now the string must be converted into a 'date' object
         // we use the 'create_from_string' creator of factory 'simple_date' to do that
         // if the string is not a valid date then an error is returned
         fa_simple_date.create_from_string ( &amp;
            string = date_in_file ) &amp;
            ( o_result = o_result &amp;
            o_error = o_error )
      end
   end

end service</pre><p>To use the above command we will now create another command that simply displays the date of the last backup on the system console. The code shown below should be self-explanatory:</p><pre class="programlisting">service error_handling_examples

   command display_last_backup_date
      script

         // first we check the existence of the file
         if not a_last_backup_date_file.exists then
            system.console.write_line ( """Last backup date is unknown, because file "{{a_last_backup_date_file.to_string}}" doesn't exist!""" )
            exit script
         end if
         
         // use 'co_restore_date_from_file' to read date from file
         var simple_date last_backup_date
         var resource_error error
         co_restore_date_from_file ( a_last_backup_date_file ) &amp;
            ( v_last_backup_date = o_result &amp;
            v_error = o_error )

         // check if the operation succeeded
         if v_error =r void then
            // ok. no problem.
            system.console.write_line ( "Last backup was done on " &amp; v_last_backup_date.to_string )
         else
            // problem!
            system.console.write_line ( """Last backup date could not be defined!
The following error occured when reading from file "{{a_last_backup_date_file.to_string}}":
{{v_error.to_string}}""" )
         end if
      end
   end

end service</pre></div></div><div class="navfooter"><hr><table width="100%" summary="Navigation footer"><tr><td width="40%" align="left"><a accesskey="p" href="program_error.html">Prev</a> </td><td width="20%" align="center"><a accesskey="u" href="error_handling.html">Up</a></td><td width="40%" align="right"> <a accesskey="n" href="user_input_error.html">Next</a></td></tr><tr><td width="40%" align="left" valign="top">Program error </td><td width="20%" align="center"><a accesskey="h" href="index.html">Home</a></td><td width="40%" align="right" valign="top"> User input error</td></tr></table></div></body></html>
